FROM python:3.12-slim
# LibreOffice for PDF conversion
RUN apt-get update && apt-get install -y --no-install-recommends libreoffice && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY api ./api
CMD ["celery", "-A", "api.tasks.celery_app", "worker", "-l", "INFO"]
